[project]
name = "db-updates"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb==1.3.2",
    "numpy>=1.2.1,<2",
    "pandas>=2.1.2",
    "polars[pyarrow]>=1.29.0",
]
